### ISSUE TITLE
Get Discourse discussion forums working as email lists

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/worldwidetelescope.github.io#1]

**Comment by kfogel** [comment]
By the way, @martinwoodward, search for email from me in mid-September with Subject line "How to post by email to Discourse for AAS Task Force forum?" for context.

**Comment by martinwoodward** [comment]
Been digging into emails with Discourse. Works a little differently than I think we where thinking (i.e. quite different to Google groups).

By default, all new users are now configured to get notifications via email about new messages to the forums while they are away. To stop these email notifications, click on your avatar on the top right hand side of the website, and select “Profile” then “Preferences”. In the middle there is an Email section where you can control what messages you will receive. You can configure to get digests or just notifications for posts you watch or when someone @mentions you in a message.

When you receive an email notification about a new post, you are able to reply to that email and the message will go into the web forums (and others will get notified via email).

If you want to start a new message then it must go into one of the categories, for example feedback@wwtforums.dotnetfoundation.org or aas-task-force@wwtforums.dotnetfoundation.org.   Emails sent to discussion@wwtforums.dotnetfoundation.org will be in Uncategorized. The way we have the email features configured at the moment, users must have established trust with the web based forums system before they can create new threads by email. This is designed to be a spam prevention feature – however we can turn this setting down or even configure certain categories so that anyone can send an email message to them regardless of if they have signed up with the forum or not.

For more information about email settings/configuration then take a look at https://meta.discourse.org/t/set-up-email-in-start-topic-via-email/27686 and let me know if we want to change the configuration at all.

**Comment by kfogel** [comment]
On Oct 22, 2015 6:31 PM, "Martin Woodward" <notifications@github.com> wrote:
>
> Been digging into emails with Discourse. Works a little differently than
I think we where thinking (i.e. quite different to Google groups).
>
> By default, all new users are now configured to get notifications via
email about new messages to the forums while they are away. To stop these
email notifications, click on your avatar on the top right hand side of the
website, and select “Profile” then “Preferences”. In the middle there is an
Email section where you can control what messages you will receive. You can
configure to get digests or just notifications for posts you watch or when
someone @mentions you in a message.

Thanks, Martin.  Hmm <ponders>... This sounds very different from the
"subscribe to a mailing list" paradigm that people are used to (even though
in the population as a whole the percentage of people who are used to this
may be gradually declining, the percentage among people who after likely
WWT users and contributors is probably high).

I gather from the above that new users are automatically subscribed to all
new threads anywhere on forums.worldwidetelescope.org?  E.g., there's no
way to subscribe just to new posts for just code contributors?  (What in
another system we would have called the "dev mailing list".)

> When you receive an email notification about a new post, you are able to
reply to that email and the message will go into the web forums (and others
will get notified via email).

This part sounds fine, and like it complies with the Principle Of Least
Surprise.

> If you want to start a new message then it must go into one of the
categories, for example feedback@wwtforums.dotnetfoundation.org or
aas-task-force@wwtforums.dotnetfoundation.org. Emails sent to
discussion@wwtforums.dotnetfoundation.org will be in Uncategorized. The way
we have the email features configured at the moment, users must have
established trust with the web based forums system before they can create
new threads by email. This is designed to be a spam prevention feature –
however we can turn this setting down or even configure certain categories
so that anyone can send an email message to them regardless of if they have
signed up with the forum or not.

Okay, so each "category" here is, more or less, the equivalent of mailing
lists -- except one can't subscribe to just that category?  Or can one?
Because if one can, then maybe the right way to do new user signup is to
ask people, when they create their account, which categories they'd like to
be subscribed to email notifications for.

Also: the domain people send to is not "@forums.worldwidetelescope.org",
but instead "@wwtforums.dotnetfoundation.org"?  That's a bit of
implementation detail poking out into userland that it'd be nice to avoid
if we can...

> For more information about email settings/configuration then take a look
at https://meta.discourse.org/t/set-up-email-in-start-topic-via-email/27686
and let me know if we want to change the configuration at all.

Ah, okay, thanks.  I'm on a tiny screen and slow connection right now, but
I'll take a look at that tomorrow and see if it answers any of my questions
above.

Best regards,
-Karl

**Comment by kfogel** [comment]
Whew.  So I've read the page on this now (the one you pointed to, Martin).
Basically, starting new threads via email is not well-supported in
Discourse.  One can hack it up to make it work, sort of, but it will always
be fragile.

This isn't necessarily a showstopper; we may not need to be so
email-centric.  But we should think about it.  I've put it on my "discuss
in person in Boston" list!

-K
